### ISSUE TITLE
Swagger file generation fails for arrays

### ISSUE THREAD

**Issue by AlexPirtea** [aliencube/AzureFunctions.Extensions#10] opened 2019-02-13 13:23 UTC
Aliencube.AzureFunctions.Extensions.OpenApi  version: 1.3.0

When request DTOs contain arrays the following error gets thrown:

`[13.02.2019 13:16:28] Executed 'RenderSwaggerDocument' (Failed, Id=fb5e9696-1da8-4267-a434-696e6b1fad40)
[13.02.2019 13:16:28] System.Private.CoreLib: Exception while executing function: RenderSwaggerDocument. Aliencube.AzureFunctions.Extensions.OpenApi: Index was outside the bounds of the array.`

Example request dto:
```
    public class RequestDto
    {
        public int[] Array { get; set; }
    }
```
Example function:
```
        [FunctionName(nameof(Run))]
        [OpenApiOperation("add", "sample")]
        [OpenApiRequestBody("application/json", typeof(RequestDto))]
        [OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(string))]
        public static async Task<ActionResult<string>> Run([HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "") ] RequestDto poco)
        {
            return string.Empty;
        }
```

My RenderSwaggerDocument function:
```
        [FunctionName(nameof(RenderSwaggerDocument))]
        [OpenApiIgnore]
        public static async Task<IActionResult> RenderSwaggerDocument([HttpTrigger(AuthorizationLevel.Function, "get", Route = "swagger.json")]
            HttpRequest req)
        {
            var helper = new DocumentHelper();
            var document = new Document(helper);
            var result = await document.InitialiseDocument()
                                       .AddMetadata(new OpenApiInfo { Title = "My API", Version = "v1" })
                                       .AddServer(req, "api")
                                       .Build(Assembly.GetExecutingAssembly())
                                       .RenderAsync(OpenApiSpecVersion.OpenApi2_0, OpenApiFormat.Json)
                                       .ConfigureAwait(false);
            var response = new ContentResult()
            {
                Content = result,
                ContentType = "application/json",
                StatusCode = (int)HttpStatusCode.OK
            };

            return response;
        }
```

**Comment by justinyoo** [comment] 2019-02-14 05:09
@AlexPirtea Thanks for raising this issue!

Have you tried `List<int>` instead? If that works, please use this in the meantime. I'll fix this is ASAP.

**Comment by Ozzian** [comment] 2019-02-18 10:37
To help a bit: The problem is in OpenApiSchemaExtensions class, ToOpenApiSchema method.

`type.GetGenericArguments()[0];` throws exception for regular array. To fix this you can use `GetElementType()`.

working example.
```
 if (typeof(IList).IsAssignableFrom(type))
            {
                schema.Type = "array";

                var elementType = type.GetElementType() ?? type.GetGenericArguments()[0];
                schema.Items = elementType.ToOpenApiSchema();

                return schema;
            }
```

**Comment by AlexPirtea** [comment] 2019-02-18 15:42
> @AlexPirtea Thanks for raising this issue!
> 
> Have you tried `List<int>` instead? If that works, please use this in the meantime. I'll fix this is ASAP.

Lists work

**Comment by justinyoo** [comment] 2019-02-28 12:38
@AlexPirtea I've fixed to allow array, on top of `List<T>`. This will be released soon. Thanks for waiting.

**Closed as completed** 2019-02-28 12:58 UTC
Labels: bug, open api
