### ISSUE TITLE
Swagger generation for JObject fails (due to IDictionary cast)

### ISSUE THREAD

**Issue by JoschaMetze** [aliencube/AzureFunctions.Extensions#29] opened 2019-04-23 12:19 UTC
If a model class for an operation contains a JObject property (or JObject itself) the generation fails with an index out of bounds exception. I suppose this is linked to ```  schema.AdditionalProperties = type.GetGenericArguments()[1].ToOpenApiSchema();```(line 61 of OpenApiSchemaExtensions.cs) as JObject implements IDictionary but has no generic arguments itself.

I suggest either checking for JObject itself (as you are already referencing Newtonsoft.Json in that file) or checking if the count of arguments from GetGenericArguments exceeds 1.

Thanks
Joscha

**Comment by justinyoo** [comment] 2019-04-26 12:39
@JoschaMetze Thanks for the comment! Would you give me some example code snippet so that I can reproduce the error on my side, please?

**Comment by JoschaMetze** [comment] 2019-05-09 11:42
Hey, of course, minimal repro:
**does work**
```cs
 [OpenApiOperation("FunctionWorks")] 
        [OpenApiResponseBody(HttpStatusCode.Unauthorized, "text/plain", typeof(string))]
        [OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(string))]
public static object FunctionWorks(){}
```
**does not work**
```cs
 [OpenApiOperation("FunctionFails")] 
        [OpenApiResponseBody(HttpStatusCode.Unauthorized, "text/plain", typeof(string))]
        [OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(JObject))]
public static object FunctionFails(){}
```

**Comment by justinyoo** [comment] 2019-05-30 14:24
@JoschaMetze Both `JObject` and `Dictionary` can't be declared at the root level like the example code above, because they don't have name. But both can be a property of a class like:

https://github.com/aliencube/AzureFunctions.Extensions/blob/75c770c4b14a0bfbdedb979de49c50ad9cc3715c/src/Aliencube.AzureFunctions.FunctionAppCommon/Models/SampleModel.cs#L53

https://github.com/aliencube/AzureFunctions.Extensions/blob/75c770c4b14a0bfbdedb979de49c50ad9cc3715c/src/Aliencube.AzureFunctions.FunctionAppCommon/Models/SampleModel.cs#L58

**Comment by justinyoo** [comment] 2019-05-30 14:28
@JoschaMetze I'll close this for now. If you need further discussion, please feel free to open this again.

**Closed as completed by justinyoo** 2019-05-30 14:28 UTC
Labels: bug, open api

**Comment by justinyoo** [comment] 2019-06-01 13:35
Now both `JObject` and `JToken` are properly rendered.

**Comment by justinyoo** [comment] 2019-06-01 13:36
@JoschaMetze Now both `JObject` and `JToken` are properly rendered.

**Comment by JoschaMetze** [comment] 2019-06-05 08:58
Thanks for fixing that 👍
